-- Schema for TaskFlow Analytics Project
-- Generated by AI Assistant

CREATE TABLE users (
    user_id VARCHAR(50) PRIMARY KEY,
    workspace_id VARCHAR(50),
    email VARCHAR(100),
    signup_date TIMESTAMP,
    account_tier VARCHAR(20), -- 'free', 'starter', 'professional', 'enterprise'
    user_role VARCHAR(20), -- 'owner', 'admin', 'member', 'guest'
    industry VARCHAR(50), -- 'tech', 'marketing', 'finance', 'healthcare', etc.
    team_size INT,
    signup_source VARCHAR(50), -- 'organic', 'paid_search', 'referral', 'sales'
    country VARCHAR(50),
    is_active BOOLEAN,
    last_login_date TIMESTAMP
);

CREATE TABLE onboarding_funnel (
    user_id VARCHAR(50) PRIMARY KEY,
    step_1_completed BOOLEAN,
    step_1_timestamp TIMESTAMP,
    step_2_completed BOOLEAN,
    step_2_timestamp TIMESTAMP,
    step_3_completed BOOLEAN,
    step_3_timestamp TIMESTAMP,
    step_4_completed BOOLEAN,
    step_4_timestamp TIMESTAMP,
    onboarding_completed BOOLEAN,
    onboarding_completion_date TIMESTAMP,
    time_to_complete_hours FLOAT,
    ab_test_variant VARCHAR(10) -- 'control', 'variant_a'
);

CREATE TABLE feature_usage (
    usage_id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50),
    feature_name VARCHAR(100),
    first_used_date TIMESTAMP,
    total_usage_count INT,
    last_used_date TIMESTAMP,
    days_since_signup_at_first_use INT
);

CREATE TABLE subscriptions (
    subscription_id VARCHAR(50) PRIMARY KEY,
    workspace_id VARCHAR(50),
    plan_type VARCHAR(20),
    mrr DECIMAL(10,2),
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    is_active BOOLEAN,
    churn_date TIMESTAMP,
    churn_reason VARCHAR(100)
);

CREATE TABLE ab_test_assignments (
    user_id VARCHAR(50) PRIMARY KEY,
    test_name VARCHAR(100),
    variant VARCHAR(20), -- 'control' or 'variant_a'
    assignment_date TIMESTAMP,
    converted BOOLEAN,
    conversion_date TIMESTAMP
);
